/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cliente;

import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author Sistemas
 */
public class Agregar_Numeros extends javax.swing.JFrame {

    public int numeros[] = new int[100];
    public int indice = 0;
    
    /**
     * Creates new form Agregar_cliente
     */
    public Agregar_Numeros() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        numero = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Resultado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jBtAgregar = new javax.swing.JButton();
        jBtOrdenar = new javax.swing.JButton();
        jBtVisualizar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroActionPerformed(evt);
            }
        });
        numero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numeroKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        jLabel2.setText("Digite su numero");

        Resultado.setBackground(new java.awt.Color(255, 255, 255));
        Resultado.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        jLabel1.setText("Resultado");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(Resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 160));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jBtAgregar.setBackground(new java.awt.Color(255, 255, 204));
        jBtAgregar.setText("Agregar");
        jBtAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtAgregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtAgregarMouseExited(evt);
            }
        });
        jBtAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtAgregarActionPerformed(evt);
            }
        });

        jBtOrdenar.setBackground(new java.awt.Color(153, 0, 0));
        jBtOrdenar.setForeground(new java.awt.Color(255, 255, 255));
        jBtOrdenar.setText("Ordenar");
        jBtOrdenar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtOrdenarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtOrdenarMouseExited(evt);
            }
        });
        jBtOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtOrdenarActionPerformed(evt);
            }
        });

        jBtVisualizar.setBackground(new java.awt.Color(0, 0, 255));
        jBtVisualizar.setForeground(new java.awt.Color(255, 255, 255));
        jBtVisualizar.setText("Visualizar");
        jBtVisualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtVisualizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtVisualizarMouseExited(evt);
            }
        });
        jBtVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtVisualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtVisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtOrdenar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBtOrdenar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtVisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 570, 160));

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 620, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroActionPerformed

    private void jBtVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtVisualizarActionPerformed
        // TODO add your handling code here:
        String mensaje=" ";
        for (int i=0; i<indice; i++)
        {
            mensaje=mensaje+numeros[i]+"-";
        }
        Resultado.setText(mensaje);

    }//GEN-LAST:event_jBtVisualizarActionPerformed

    private void jBtOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtOrdenarActionPerformed
        // TODO add your handling code here:
        for(int i=0; i < (indice-1)  ;i ++)
        {
            for (int j=0;j<(indice-1);j++)
            {
                if (numeros[j]> numeros [j+1])
                {
                    int aux= numeros[j];
                    numeros[j]=numeros[j+1];
                    numeros[j+1]= aux;
                }
            }
        }
        // Mostrar la lista ordenada
        String mensajeLista = " ";
        for (int i=0;i<indice;i++)
        {
            mensajeLista = mensajeLista + numeros [i]+"-";
            Resultado.setText(mensajeLista);
        }
    }//GEN-LAST:event_jBtOrdenarActionPerformed

    private void jBtAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtAgregarActionPerformed
        // TODO add your handling code here:
        //Resultado.setText(numero.getText());
        if (!validarNumeros(numero.getText().trim()))
        {
            JOptionPane.showMessageDialog(rootPane, "El dato es invalido");
            numero.setText("");
        }
        else
        JOptionPane.showMessageDialog(rootPane, "El dato es valido");
        numeros [indice]=Integer.parseInt(numero.getText());
        indice++;
        numero.setText("");
    }//GEN-LAST:event_jBtAgregarActionPerformed

    private void numeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numeroKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar())){
          evt.consume();
        }
    }//GEN-LAST:event_numeroKeyTyped

    private void jBtAgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtAgregarMouseEntered
        // TODO add your handling code here:
        jBtAgregar.setBackground(new java.awt.Color(241, 196, 15));
        jBtAgregar.setForeground(new java.awt.Color(41, 128, 185));
    }//GEN-LAST:event_jBtAgregarMouseEntered

    private void jBtAgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtAgregarMouseExited
        // TODO add your handling code here:
        jBtAgregar.setBackground(new java.awt.Color(155, 89, 182));
        jBtAgregar.setForeground(new java.awt.Color(22, 160, 133));
    }//GEN-LAST:event_jBtAgregarMouseExited

    private void jBtVisualizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtVisualizarMouseEntered
        // TODO add your handling code here:
        jBtVisualizar.setBackground(new java.awt.Color(230, 126, 34));
        jBtVisualizar.setForeground(new java.awt.Color(44, 62, 80));
    }//GEN-LAST:event_jBtVisualizarMouseEntered

    private void jBtVisualizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtVisualizarMouseExited
        // TODO add your handling code here:
        jBtVisualizar.setBackground(new java.awt.Color(192, 57, 43));
        jBtVisualizar.setForeground(new java.awt.Color(236, 240, 241));
    }//GEN-LAST:event_jBtVisualizarMouseExited

    private void jBtOrdenarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtOrdenarMouseEntered
        // TODO add your handling code here:
      jBtOrdenar.setBackground(new java.awt.Color(26, 188, 156));
        jBtOrdenar.setForeground(new java.awt.Color(52, 73, 94));  
    }//GEN-LAST:event_jBtOrdenarMouseEntered

    private void jBtOrdenarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtOrdenarMouseExited
        // TODO add your handling code here:
        jBtOrdenar.setBackground(new java.awt.Color(241, 196, 15));
        jBtOrdenar.setForeground(new java.awt.Color(127, 140, 141));  
    }//GEN-LAST:event_jBtOrdenarMouseExited
public static boolean validarNumeros(String datos)
    {
        return datos.matches("[0-9]*");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agregar_Numeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agregar_Numeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agregar_Numeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agregar_Numeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agregar_Numeros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Resultado;
    private javax.swing.JButton jBtAgregar;
    private javax.swing.JButton jBtOrdenar;
    private javax.swing.JButton jBtVisualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField numero;
    // End of variables declaration//GEN-END:variables
}
